coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 2%
    patch:
      default:
        informational: false
        target: 90%
        threshold: 1%
    changes: false
